# Generated by Django 5.1.3 on 2025-03-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Surec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField()),
                ("aktif", models.BooleanField(default=True)),
                ("kosullar", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tedarikci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("adres", models.TextField(blank=True, null=True)),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stok", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SatinAlmaSiparisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toplam_tutar", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("taslak", "Taslak"),
                            ("onay_bekliyor", "Onay Bekliyor"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("revizyon_bekliyor", "Revizyon Bekliyor"),
                        ],
                        default="taslak",
                        max_length=20,
                    ),
                ),
                ("red_nedeni", models.TextField(blank=True, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_olusturulan_siparisler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "son_islem_yapan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tedarik_islem_yapilan_siparisler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onay_sureci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tedarik.surec",
                    ),
                ),
                (
                    "tedarikci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tedarik.tedarikci",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("sira", models.IntegerField()),
                ("kosul", models.JSONField(blank=True, null=True)),
                ("sonraki_adim_kosulu", models.JSONField(blank=True, null=True)),
                (
                    "onaylayanlar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tedarik_onay_adimlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departmanlar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tedarik_onay_adimlari",
                        to="tedarik.departman",
                    ),
                ),
                (
                    "surec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_adimlari",
                        to="tedarik.surec",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurecDurumu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("notlar", models.TextField(blank=True, null=True)),
                ("red_nedeni", models.TextField(blank=True, null=True)),
                ("baslangic_tarihi", models.DateTimeField(auto_now_add=True)),
                ("tamamlanma_tarihi", models.DateTimeField(blank=True, null=True)),
                (
                    "mevcut_adim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tedarik.adim",
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_surec_durumu",
                        to="tedarik.satinalmasiparisi",
                    ),
                ),
                (
                    "son_islem_yapan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tedarik_islem_yapilan_durumlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tedarik.surec"
                    ),
                ),
                (
                    "tamamlanan_adimlar",
                    models.ManyToManyField(
                        related_name="tamamlanan_durumlar", to="tedarik.adim"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeriGonderme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("red_nedeni", models.TextField()),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "geri_gonderen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_geri_gondermeler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec_durumu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_geri_gondermeler",
                        to="tedarik.surecdurumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geri Gönderme",
                "verbose_name_plural": "Geri Göndermeler",
            },
        ),
        migrations.CreateModel(
            name="Dosya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosya", models.FileField(upload_to="surec_dosyalar/")),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "yukleyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_dosyalar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec_durumu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tedarik_dosyalar",
                        to="tedarik.surecdurumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dosya",
                "verbose_name_plural": "Dosyalar",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tedarik_calisanlar",
                        to="tedarik.departman",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
