# Generated by Django 5.1.3 on 2025-03-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="satinalmasiparisi",
            name="red_nedeni",
        ),
        migrations.AlterField(
            model_name="satinalmasiparisi",
            name="onay_sureci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tedarik_siparisler",
                to="tedarik.surec",
            ),
        ),
    ]
