# Generated by Django 5.1.3 on 2025-03-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0002_remove_satinalmasiparisi_red_nedeni_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="satinalmasiparisi",
            name="tedarikci",
        ),
        migrations.CreateModel(
            name="Proje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                (
                    "surec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proje_surecler",
                        to="tedarik.surec",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="satinalmasiparisi",
            name="proje",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tedarik.proje",
            ),
        ),
    ]
