# Generated by Django 5.1.3 on 2025-03-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0003_remove_satinalmasiparisi_tedarikci_proje_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurecYorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yorum", models.TextField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                ("dosyalar", models.ManyToManyField(blank=True, to="tedarik.dosya")),
                (
                    "surec_durumu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="tedarik.surecdurumu",
                    ),
                ),
                (
                    "yazan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Süreç Yorumu",
                "verbose_name_plural": "Süreç Yorumları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
