# Generated by Django 5.1.3 on 2025-03-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0004_surecyorum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="satinalmasiparisi",
            options={
                "ordering": ["-olusturma_tarihi"],
                "verbose_name": "Satin Alma Siparişi",
                "verbose_name_plural": "Satin Alma Siparişleri",
            },
        ),
        migrations.RemoveField(
            model_name="surecyorum",
            name="surec_durumu",
        ),
        migrations.AddField(
            model_name="surecyorum",
            name="adim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yorumlar",
                to="tedarik.adim",
            ),
        ),
    ]
