# Generated by Django 5.1.3 on 2025-03-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0005_alter_satinalmasiparisi_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surecyorum",
            name="surec_durumu",
            field=models.ForeignKey(
                default=30,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yorumlar",
                to="tedarik.surecdurumu",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surecyorum",
            name="adim",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yorumlar",
                to="tedarik.adim",
            ),
            preserve_default=False,
        ),
    ]
