# Generated by Django 5.1.3 on 2025-03-14 21:43

import tedarik.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0006_surecyorum_surec_durumu_alter_surecyorum_adim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SatinAlmaSiparisi",
            new_name="MalzemeTalep",
        ),
        migrations.AlterField(
            model_name="dosya",
            name="dosya",
            field=models.FileField(upload_to=tedarik.models.surec_dosya_yolu),
        ),
    ]
