# Generated by Django 5.1.3 on 2025-03-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0007_rename_satinalmasiparisi_malzemetalep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MalzemeKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Malzeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("birim", models.CharField(max_length=255)),
                ("stok", models.IntegerField(blank=True, null=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="malzemeler",
                        to="tedarik.malzemekategori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MalzemeTalepSatir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "malzeme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talep_satirlar",
                        to="tedarik.malzeme",
                    ),
                ),
                (
                    "talep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satirlar",
                        to="tedarik.malzemetalep",
                    ),
                ),
            ],
        ),
    ]
