# Generated by Django 5.1.3 on 2025-03-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0008_malzemekategori_malzeme_malzemetalepsatir"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="malzemetalep",
            name="toplam_tutar",
        ),
    ]
