# Generated by Django 5.1.3 on 2025-03-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0009_remove_malzemetalep_toplam_tutar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="malzemetalep",
            name="onay_sureci",
        ),
    ]
