# Generated by Django 5.1.3 on 2025-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tedarik", "0010_remove_malzemetalep_onay_sureci"),
    ]

    operations = [
        migrations.AddField(
            model_name="malzemetalep",
            name="aciklama",
            field=models.TextField(blank=True, null=True),
        ),
    ]
