# Generated by Django 5.1.3 on 2025-03-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SatinAlmaSiparisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toplam_tutar", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("taslak", "Taslak"),
                            ("onay_bekliyor", "Onay Bekliyor"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("revizyon_bekliyor", "Revizyon Bekliyor"),
                        ],
                        default="taslak",
                        max_length=20,
                    ),
                ),
                ("red_nedeni", models.TextField(blank=True, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="olusturulan_siparisler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Satın Alma Siparişi",
                "verbose_name_plural": "Satın Alma Siparişleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
