# Generated by Django 5.1.3 on 2025-03-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("siparis", "0001_initial"),
        ("workflow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="satinalmasiparisi",
            name="onay_sureci",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.surec",
            ),
        ),
        migrations.AddField(
            model_name="satinalmasiparisi",
            name="son_islem_yapan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="islem_yapilan_siparisler",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="satinalmasiparisi",
            name="tedarikci",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tedarikci"
            ),
        ),
    ]
