# Generated by Django 5.1.3 on 2025-03-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Surec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                ("kosullar", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Süreç",
                "verbose_name_plural": "Süreçler",
            },
        ),
        migrations.CreateModel(
            name="Adim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("sira", models.IntegerField()),
                ("kosul", models.JSONField(blank=True, null=True)),
                ("sonraki_adim_kosulu", models.JSONField(blank=True, null=True)),
                (
                    "departmanlar",
                    models.ManyToManyField(
                        blank=True, related_name="onay_adimlari", to="core.departman"
                    ),
                ),
                (
                    "onaylayanlar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="onay_adimlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adimlar",
                        to="workflow.surec",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adım",
                "verbose_name_plural": "Adımlar",
                "ordering": ["surec", "sira"],
            },
        ),
        migrations.CreateModel(
            name="SurecDurumu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                ("notlar", models.TextField(blank=True, null=True)),
                ("red_nedeni", models.TextField(blank=True, null=True)),
                ("baslangic_tarihi", models.DateTimeField(auto_now_add=True)),
                ("tamamlanma_tarihi", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "mevcut_adim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.adim",
                    ),
                ),
                (
                    "son_islem_yapan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islem_yapilan_durumlar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.surec"
                    ),
                ),
                (
                    "tamamlanan_adimlar",
                    models.ManyToManyField(
                        related_name="tamamlanan_durumlar", to="workflow.adim"
                    ),
                ),
            ],
            options={
                "verbose_name": "Süreç Durumu",
                "verbose_name_plural": "Süreç Durumları",
            },
        ),
        migrations.CreateModel(
            name="GeriGonderme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("red_nedeni", models.TextField()),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "geri_gonderen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec_durumu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geri_gondermeler",
                        to="workflow.surecdurumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geri Gönderme",
                "verbose_name_plural": "Geri Göndermeler",
            },
        ),
        migrations.CreateModel(
            name="Dosya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosya", models.FileField(upload_to="surec_dosyalar/")),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "yukleyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surec_durumu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosyalar",
                        to="workflow.surecdurumu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dosya",
                "verbose_name_plural": "Dosyalar",
            },
        ),
    ]
